print("Welcome to your Adventure Story Simulator.")
print ()
print("I am going to ask you a bunch of questions and then create an epic story with you as the star.")

print()
name = input("What is your name? ")
print()
enemyName = input("What is your enemy's name? ")
print()
superPower = input("What is your super power? ")
print()
live = input("Where do you live? ")
print()
food = input("What is your favorite food? ")
print(f"Hello \033[31m{name}, \033[0myour ability to \033[35m{superPower} \033[0mwill make sure you never have to look at \033[32m{enemyName}, \033[0magain. Go eat \033food as you walk down the streets of \033[37m{live}, and use, \033[32m{superPower} \033[37mfor good and not evil!")
print()
